version: '3'
services:
  hugo:
    build:
      context: .
    volumes:
      - .:/src
      - ./public:/src/public
    ports:
      - "1313:1313"
    command: ["hugo", "server", "--bind", "0.0.0.0", "--port", "1313", "--baseURL", "http://127.0.0.1/"]
